### ISSUE TITLE
Snapshot store

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#15]
Should be pretty straightforward, and similar to r2dbc.

* persistenceId as partition key, and no sort key, update existing item
* separate table
* max item size 400 kB
* prepare for starting projection from snapshot by including EntityTypeSlice attribute (slice index on snapshots)

**Comment by pvlugter** [comment]
I'll take a look at adding this.

**Comment by pvlugter** [comment]
Do we want to do anything about max item size now? For snapshots, would be straightforward to store over multiple item parts — but if something is over 400 kB, then multiple parts would likely trip the 1000 WCU per second partition limit. We may also need to calculate item sizes ourselves. So shall we just let DynamoDB return errors for too-large snapshot items, and have a separate issue for providing an S3-based snapshot store that people can switch to?
