### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#16]
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/security-iam.html

also note `credentialsProvider(EnvironmentVariableCredentialsProvider.create())` of DynamoDbAsyncClient

**Comment by pvlugter** [comment]
Lots of ways to provide credentials. Maybe the default credentials provider (not specifying anything explicitly) covers what we want to support anyway (looks at system properties, environment variables, web identity token, credentials file, container service, metadata service)?

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html

Expect that just works when deploying within AWS or from a development machine that's already configured for AWS if needing to access from outside.

**Comment by pvlugter** [comment]
See that the old dynamodb plugin also used and recommended the default credentials:

https://github.com/akka/akka-persistence-dynamodb/blob/27f9e016b2cc610e66e28b75bb7305d1e5ef4cee/src/main/resources/reference.conf#L46-L52

**Comment by pvlugter** [comment]
Not sure that we need config overrides for this, can always set environment variables or system properties to override with the default credentials provider.

**Comment by pvlugter** [comment]
Similarly for region. The default is to check a system property, environment variable, credentials or config files, or EC2 metadata service.

So we may only want our own config overrides for local testing.

**Comment by pvlugter** [comment]
We haven't tested in AWS yet, but should be done.
