### ISSUE TITLE
TimstampOffsetBySlice in Projection over gRPC

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#19]
The TimestampOffsetBySlice should be handled by Projection over gRPC.

Right now it works the first time because NoOffset, after that:
```
IllegalArgumentException: Expected TimestampOffset or NoOffset, but got [akka.persistence.dynamodb.internal.TimestampOffsetBySlice@2eb21b72]
````

**Comment by pvlugter** [comment]
I'll add TimestampOffsetBySlice to akka-persistence-query, and update gRPC projections to support it.

Do we also want to support in r2dbc, so that it could be r2dbc on one side and dynamodb on the other?

**Comment by pvlugter** [comment]
Updates:

- https://github.com/akka/akka/pull/32479
- https://github.com/akka/akka-projection/pull/1181
- https://github.com/lightbend/akka-persistence-dynamodb-private/pull/72

**Comment by patriknw** [comment]
> Do we also want to support in r2dbc, so that it could be r2dbc on one side and dynamodb on the other?

I think that can wait until someone is requesting it. Wouldn't that also mean changing the R2dbcOffsetStore to be able to return TimstampOffsetBySlice as first offset?

**Comment by pvlugter** [comment]
Yes, r2dbc would need to properly support TimestampOffsetBySlice, or we would at least need a translation between them. For TimestampOffsetBySlice to TimestampOffset, just take the earliest. For the other way around, I guess need to assume the TimestampOffset is the earliest for all slices (could fill the map with all possible slices, or have it default in some way).

But requiring projections over gRPC to be the same implementation on both sides for now sounds good.

**Comment by pvlugter** [comment]
Rather than including TimestampOffsetBySlice in akka-persistence-query, we could possibly make the offset pluggable in gRPC projections? So the implementation takes care of serialization, and can use its own types.

**Comment by pvlugter** [comment]
Changes are done for this. Just needs an akka-projection release.
