### ISSUE TITLE
Projection atLeastOnce

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#22]
I don't see that we would need it. atLeastOnceAsync should be enough. If the handler want to use DynamoDB it can use the DynamoDBAsyncClient. Same with groupedWithin.

**Comment by pvlugter** [comment]
Makes sense. Shall we also rename the current `atLeastOnceAsync` to just `atLeastOnce` to simplify?

We've also copied over some docs referencing `atLeastOnce`:

https://github.com/lightbend/akka-persistence-dynamodb-private/blob/a0e86fb04fa95f172b4f9799144740794594b8ca/projection/src/main/scala/akka/projection/dynamodb/scaladsl/DynamoDBProjection.scala#L31-L32
