### ISSUE TITLE
Cleanup tool

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#26]
Cleanup tool was requested by customer

**Comment by pvlugter** [comment]
We have a cleanup tool with the core operations for event sourced entities, for deleting events and snapshots, and also setting TTL expiration timestamps. It doesn't currently support the before-timestamp operations. We also don't have current persistent id queries in general. We may not end up supporting these anyway, given the extra tables/indexes that we'll likely need for this. Closing this as completed for the original request. Can be extended as needed after user feedback.
