### ISSUE TITLE
TTL

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#27]
Customer was requesting TTL feature. Not exactly clear what would be marked for later removal by DynamoDB TTL.

* events before snapshot
* all events and snapshot of an entity (persistenceId)
* as alternative to ordinary deletes

Maybe related to #26

**Comment by pvlugter** [comment]
Setting expiry via the cleanup tool, using TTL in place of deletes, and adding TTL when writing events or snapshots are all supported. An option to check expiry when reading events or snapshots has also been added, to treat items as already expired before DynamoDB does the actual deletion.

I think we've covered enough the first version of this feature. Have tested against actual DynamoDB as well, with TTL enabled. Closing, and we can refine or extend based on user feedback.
