### ISSUE TITLE
CreateTables utility

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#28]
I added a basic CreateTables utiltiy, but I'm not sure if we should recommend using that or if tables are always created and provisioned via management console or cli? It could still be useful for testing though.

**Comment by pvlugter** [comment]
Sounds useful to provide the utility. And can document the equivalent AWS CLI commands, or requirements to do it via the management console.

**Comment by pvlugter** [comment]
The CreateTables utility described in docs for creating tables locally in #51. Table definitions and the `aws` commands also added to the docs for each plugin.

**Comment by pvlugter** [comment]
Some configurability added in #60. We could also consider having this driven via config, and generic for creating any tables and indexes. We're unsure if it makes sense to create tables programmatically anyway, given possible raciness.

**Comment by pvlugter** [comment]
We have the CreateTables utility in place, documented for creating tables locally. Docs include table and index descriptions, and `aws` command examples. Basic configuration also possible (not needed for local though). Closing this as covered at this point.
