### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#42]
* Would the shopping cart sample work for performance tests?
* Should we add http routes to the sample to make it easier to test?
* K6 as load client?

**Comment by pvlugter** [comment]
A bunch of performance testing has been completed now. Everything looks ok. Latencies are predictable, though not as tight as we see with RDS Postgres and R2DBC plugin. Main limitation is probably that the client is still HTTP/1 based. Would be interesting to try things when an HTTP/2 client is supported for DynamoDB, or maybe trying with a pipelining client.

Will add some results and screenshots to this issue.

**Comment by pvlugter** [comment]
Testing with the inventory sample, also used for some earlier testing. Load test at ~7k rps and peaks ~14k rps. Can see the increased latency at higher throughput.

<img width="1312" alt="load-test-01-gatling-summary" src="https://github.com/user-attachments/assets/5ea5641a-a277-4695-af8b-887fab24808d">

<img width="1329" alt="load-test-01-gatling-graphs" src="https://github.com/user-attachments/assets/dfe2a13f-e16d-4b50-b3f9-2aaf1af6dac7">

<img width="1903" alt="load-test-01-response-time" src="https://github.com/user-attachments/assets/27ce0d25-76f4-473a-b790-ec840cfd0c5f">

<img width="1899" alt="load-test-01-persistence-time" src="https://github.com/user-attachments/assets/2b5dc2a5-58be-4176-859a-f0da836f367e">

**Comment by pvlugter** [comment]
Same load test with more resources. Before 9 x 4 CPU, now 16 x 4 CPU nodes.

<img width="1309" alt="load-test-02-gatling-summary" src="https://github.com/user-attachments/assets/9d1e7567-1d36-43b7-b6a7-a0923619983c">

<img width="1327" alt="load-test-02-gatling-graphs" src="https://github.com/user-attachments/assets/c7a5393c-3197-43ad-b396-d0b618be54dd">

<img width="1905" alt="load-test-02-response-time" src="https://github.com/user-attachments/assets/3e15a348-e9ff-4093-8990-550d80cda1c6">

<img width="1901" alt="load-test-02-persistence-time" src="https://github.com/user-attachments/assets/355b8a97-f31c-4761-ae5c-b9787b38ae7d">

**Comment by pvlugter** [comment]
Soak test at reasonable throughput. The latency spikes after ~10 minutes are in all of the initial tests, and with throughput close to capacity. Expect this is DynamoDB splitting partitions.

<img width="1312" alt="soak-test-01-gatling-summary" src="https://github.com/user-attachments/assets/c659416a-a97f-4cbe-a776-55878d30cfa6">

<img width="1333" alt="soak-test-01-gatling-graphs" src="https://github.com/user-attachments/assets/e8a787f0-fb5b-4782-aa66-c1d6d3954cf2">

<img width="1903" alt="soak-test-01-response-time" src="https://github.com/user-attachments/assets/5c7b8fae-4111-4da4-9b52-2ae7e783e636">

<img width="1900" alt="soak-test-01-persistence-time" src="https://github.com/user-attachments/assets/19758a55-96c9-4051-b95f-7870dbda444b">

**Comment by pvlugter** [comment]
A second soak test running on the same tables and deployment, is now regular:

<img width="1311" alt="soak-test-02-gatling-summary" src="https://github.com/user-attachments/assets/a062dc22-518a-4485-aac1-6f0f2c0a90b1">

<img width="1331" alt="soak-test-02-gatling-graphs" src="https://github.com/user-attachments/assets/4b5f3870-3c91-4a8d-ad07-80b133d75fd0">

<img width="1905" alt="soak-test-02-response-time" src="https://github.com/user-attachments/assets/f6f98297-5e48-4f66-ba0a-bd93bb83567b">

<img width="1905" alt="soak-test-02-persistence-time" src="https://github.com/user-attachments/assets/49dced3b-1a06-4bc6-a33b-fd1671bd2fe3">

**Comment by pvlugter** [comment]
Under provisioned test, where the throughput is higher than the provisioned capacity on the table.

At first DynamoDB will allow the higher throughput, using burst capacity, before throttling the writes.

The throttled write errors will retry in the DynamoDB client. In this test, enough progress is made that the journal circuit breaker is not tripped, but requests timing out on ask timeout of 5 seconds.

<img width="1621" alt="under-provisioned-01-write-usage" src="https://github.com/user-attachments/assets/67cbdea8-1c2f-4335-8a14-2d2da6d9f0ba">

<img width="1626" alt="under-provisioned-01-throttling" src="https://github.com/user-attachments/assets/6f462c85-c55c-44d6-acce-6d8012bb9062">

<img width="1310" alt="under-provisioned-01-gatling-summary" src="https://github.com/user-attachments/assets/e15d0b7f-d321-4280-b7c8-e071af6a11f6">

<img width="1331" alt="under-provisioned-01-gatling-graphs" src="https://github.com/user-attachments/assets/2a2da63d-61af-4313-943c-1e4ef7d8a9aa">

<img width="1903" alt="under-provisioned-01-response-time" src="https://github.com/user-attachments/assets/fd604c93-1fd7-425f-a3f2-01de5e1571d9">

<img width="1902" alt="under-provisioned-01-persistence-time" src="https://github.com/user-attachments/assets/72c2f8bb-4be0-4b7b-ac72-bb91920ee532">

**Comment by pvlugter** [comment]
Another under provisioned test, with longer ask timeout. Open model test, so increasing number of virtual users when it can't keep up. But most of the errors are connections being refused by the load balancer in kubernetes, which will be preventing overload on the application itself.

<img width="1313" alt="under-provisioned-02-gatling-summary" src="https://github.com/user-attachments/assets/856bcd19-c62f-4fa1-8c35-d4e4750dbd0a">

<img width="1324" alt="under-provisioned-02-gatling-graphs" src="https://github.com/user-attachments/assets/d25345b4-d9c1-4ef3-ac5e-9a4d728d5ef4">

<img width="1900" alt="under-provisioned-02-response-time" src="https://github.com/user-attachments/assets/83c59447-3883-45a0-9f0b-25f0d8efc79c">

<img width="1900" alt="under-provisioned-02-persistence-time" src="https://github.com/user-attachments/assets/c8f7d6f7-2bf6-4797-be20-4eb5cf7187fb">

**Comment by pvlugter** [comment]
Test with projections. Providing there are enough resources on the application side, then things can keep up fine. If the deployment is under provisioned, then it can persist events faster than projections can keep up — with projections doing more database work given the additional backtracking queries — consumer lag (wait time in the Cinnamon metrics) will increase, and eventually projections will start failing once it gets too far behind the backtracking window.

In this test run, enough resources to maintain projections. Publishing events disabled at this throughput. Projection envelope source distinguished in the metrics (query, pubsub, or backtracking). The latency spikes part way through should be partition splitting in DynamoDB.

<img width="1329" alt="projection-test-01-gatling-graphs" src="https://github.com/user-attachments/assets/1878a0fb-f5ee-4342-99dc-44070b4b30cd">

<img width="1896" alt="projection-test-01-overview-akka-http" src="https://github.com/user-attachments/assets/5c1ddd87-4f24-4ec3-b2d9-e6bdc50b2854">

<img width="1905" alt="projection-test-01-overview-akka-persistence" src="https://github.com/user-attachments/assets/9d39f2d4-2032-499a-a776-0c9b695e2b3d">

<img width="1904" alt="projection-test-01-overview-akka-projections" src="https://github.com/user-attachments/assets/2751fc65-e020-4d56-9a8d-e915c6a6c7c5">

<img width="1900" alt="projection-test-01-overview-akka-projections-tooltip" src="https://github.com/user-attachments/assets/470bd226-ff89-4cb3-8b89-a1e7205fbfeb">

**Comment by pvlugter** [comment]
For a hotspot test, a single entity instance hotspot will likely not be throttled, given lower WCU usage. Given an average write latency of 5ms, throughput of a single entity instance can only be 200/s. With larger payloads (consuming more WCUs), or multiple entity hotspots that are mapped to the same partition by DynamoDB, could then also see the partition throughput limit throttling. Throttling errors are retryable, so will retry in the client. Shouldn't necessarily cause client errors, but increased latencies and further limiting the throughput.

**Comment by patriknw** [comment]
> eventually projections will start failing once it gets too far behind the backtracking window

Will it eventually catch up if we stop writing at high throughput?
Is this the `akka.persistence.dynamodb.query.backtracking.window`?
Or is it `akka.projection.dynamodb.offset-store.time-window`?

Maybe we can revisit the windows for dynamodb since there are some differences compared to r2dbc, such as lazy loading of offsets and each BySliceQuery is for a single slice.

**Comment by pvlugter** [comment]
Yes, that should've been that it's failing on backtracking once it's outside the offset store time window (5 minutes). Envelopes rejected from backtracking because of unexpected sequence numbers. Doesn't recover. Can be recovered by restarting with a big enough backtracking window. We saw similar with r2dbc as well.

**Comment by patriknw** [comment]
Don't know if we can improve that, but created a separate issue https://github.com/lightbend/akka-persistence-dynamodb-private/issues/67

**Comment by pvlugter** [comment]
Issues and fixes for projections falling behind are separated out. Projections are the weakest point in terms of performance, requiring plenty of resources. Otherwise I think performance testing is covered. Closing this issue.
