### ISSUE TITLE
Delete old offsets

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#45]
We don't delete any offsets yet. It's not as important as in r2dbc to delete offsets since we only load the pid/seqNr on demand. Maybe we can use DynamoDB TTL and have a long, configurable, TTL?

**Comment by pvlugter** [comment]
So a configurable TTL, which is set on each offset update. We can add this alongside the current TTL configuration. Since TTL needs to be enabled on the table, should we have the setting off by default?

**Comment by patriknw** [comment]
Sounds good to have it as configurable ttl.
